version: "3"

volumes:

   kong_data:
      driver: local
      driver_opts:
        type: 'none'
        o: 'bind'
        device: '/Users/manuel.morales/Temp/certs'
services:

# This is setting up the postgres database

  postgres:
    image: postgres:9.6
    restart: always
    container_name: kong-ee-postgres
# This command enables SSL
#    command: -c ssl=on
    networks:
      - kong-ee
    environment:
      POSTGRES_USER: kong
      POSTGRES_DB: kong
      POSTGRES_PASSWORD: kong
    ports:
      - "5432:5432/tcp"
#Running the migrations here
  kong-migrations:
    image: kong-docker-kong-enterprise-edition-docker.bintray.io/kong-enterprise-edition:2.1.3.1-alpine
    container_name: kong-ee-migrations
    command: kong migrations bootstrap
    depends_on:
      - postgres
    environment:
      KONG_DATABASE: postgres
      KONG_PASSWORD: ${KONG_PASSWORD}
      KONG_PG_DATABASE: ${KONG_PG_DATABASE:-kong}
      KONG_PG_HOST: kong-ee-postgres
      KONG_PG_PASSWORD: ${KONG_PG_PASSWORD:-kong}
      KONG_PG_USER: ${KONG_PG_USER:-kong}
      KONG_LICENSE_DATA: ${KONG_LICENSE_DATA}
      KONG_PG_SSL: "on"
      KONG_PG_SSL_VERIFY: "on"
      KONG_HEADERS: "off"
      KONG_ADMIN_GUI_FLAGS: '{"IMMUNITY_ENABLED":true}'

    links:
      - postgres:postgres
    networks:
      - kong-ee
    restart: on-failure

  kong-ee:
    image: kong-docker-kong-enterprise-edition-docker.bintray.io/kong-enterprise-edition:2.1.3.1-alpine
    user: "${KONG_USER:-root}"
    container_name: kong-ee
    volumes:
      - kong_data:/etc/kong/certs
    networks:
      - kong-ee
    depends_on:
      - postgres
      - kong-migrations
    restart: on-failure
    ports:
      - "8443:8443/tcp"
      - "8444:8444/tcp"
      - "8445:8445/tcp"
      - "8446:8446/tcp"
      - "8447:8447/tcp"
#      - "9444:9411/tcp"
    environment:
      KONG_ADMIN_GUI_LISTEN: 0.0.0.0:8445 ssl
      KONG_ADMIN_LISTEN: 0.0.0.0:8444 ssl
      KONG_PROXY_LISTEN: 0.0.0.0:8443 ssl
      KONG_SMTP_MOCK: "on"
      KONG_CASSANDRA_CONTACT_POINTS: kong-ee-cassandra
      KONG_LICENSE_DATA: ${KONG_LICENSE_DATA}
      KONG_LOG_LEVEL: debug
      KONG_ADMIN_ACCESS_LOG: /dev/stdout
      KONG_ADMIN_ERROR_LOG: /dev/stderr
      KONG_ADMIN_GUI_URL: https://localhost:8445
      KONG_DATABASE: postgres
      KONG_PG_HOST: kong-ee-postgres
      KONG_PG_DATABASE: ${KONG_PG_DATABASE:-kong}
      KONG_PG_PASSWORD: ${KONG_PG_PASSWORD:-kong}
      KONG_PG_USER: ${KONG_PG_USER:-kong}
      KONG_PROXY_ACCESS_LOG: /dev/stdout
      KONG_PROXY_ERROR_LOG: /dev/stderr
      KONG_PLUGINS: bundled
      KONG_AUDIT_LOG: "on"
      KONG_PG_SSL: "on"
      KONG_PG_SSL_VERIFY: "on"
      KONG_ADMIN_GUI_SSL_CERT: /etc/kong/certs/server.crt
      KONG_ADMIN_GUI_SSL_CERT_KEY: /etc/kong/certs/server.key
      KONG_PORTAL_GUI_SSL_CERT: /etc/kong/certs/server.crt
      KONG_PORTAL_GUI_SSL_CERT_KEY: /etc/kong/certs/server.key
      KONG_ADMIN_SSL_CERT: /etc/kong/certs/server.crt
      KONG_ADMIN_SSL_CERT_KEY: /etc/kong/certs/server.key
      KONG_SSL_CERT: /etc/kong/certs/server.crt
      KONG_SSL_CERT_KEY: /etc/kong/certs/server.key
      KONG_HEADERS: "off"

      KONG_PASSWORD: ${KONG_PASSWORD}
      KONG_ENFORCE_RBAC: "on"
      KONG_ADMIN_GUI_AUTH: basic-auth
      KONG_ADMIN_GUI_SESSION_CONF: '{ "secret":"7layer", "cookie_name":"kong_Admin_cookie", "cookie_secure":false }'
      KONG_PORTAL_EMAILS_FROM: noreply@konghq.com
      KONG_PORTAL_EMAILS_REPLY_TO: noreply@konghq.com
      KONG_PORTAL_AUTO_APPROVE: "off"
      KONG_SMTP_MOCK: "off"
      KONG_SMTP_HOST: smtp.gmail.com
      KONG_SMTP_PORT: 587
      KONG_SMTP_AUTH_TYPE: plain
      KONG_SMTP_STARTTLS: "on"
      KONG_SMTP_USERNAME: kongemailtest@gmail.com
      KONG_SMTP_PASSWORD: jNzjktjjzhzwYiQdpd2jymXV
      KONG_SMTP_ADMIN_EMAILS: noreply@konghq.com
      KONG_VITALS: "off"
      KONG_ADMIN_GUI_FLAGS: '{"IMMUNITY_ENABLED":true}'

#      KONG_VITALS_STRATEGY: database # or 'influxdb' or 'prometheus' or 'database'
#      - KONG_VITALS_TSDB_ADDRESS=influxdb:8086
      # uncomment the below lines and comment the above to use prometheus
#      KONG_VITALS_TSDB_ADDRESS: prometheus:9090
#      KONG_VITALS_STATSD_ADDRESS: statsd_exporter:9125

#This is where the portal config is
      KONG_PORTAL: "on"
      KONG_PORTAL_AUTH: basic-auth
      KONG_PORTAL_GUI_LISTEN: 0.0.0.0:8446 ssl
#      KONG_PORTAL_SESSION_CONF: '{ "secret":"layer7", "cookie_name":"portal_cookie", "cookie_secure":true", "cookie_samesite":"strict", "storage":kong }'
      KONG_PORTAL_SESSION_CONF: '{ "cookie_name": "portal_session", "secret": "layer7", "storage": "kong", "cookie_secure": true }'

      KONG_PORTAL_GUI_PROTOCOL: https
      KONG_PORTAL_GUI_HOST: localhost:8446

networks:
  kong-ee:
