version: "3"

volumes:
    kong_data: {}

services:

# This is setting up the postgres database
  postgres:
    image: postgres:9.5
    restart: always
    container_name: kong-ee-postgres
    networks:
      - kong-ee
    environment:
      POSTGRES_USER: kong
      POSTGRES_DB: kong
      POSTGRES_PASSWORD: kong
    ports:
      - "5432:5432/tcp"

# Running the migrations
  kong-migrations:
    image: kong-docker-kong-enterprise-edition-docker.bintray.io/kong-enterprise-edition:2.1.3.1-alpine
    container_name: kong-ee-migrations
    command: kong migrations bootstrap
    depends_on:
      - postgres
    environment:
      KONG_DATABASE: postgres
      KONG_PASSWORD: admin
      KONG_PG_DATABASE: ${KONG_PG_DATABASE:-kong}
      KONG_PG_HOST: kong-ee-postgres
      KONG_PG_PASSWORD: ${KONG_PG_PASSWORD:-kong}
      KONG_PG_USER: ${KONG_PG_USER:-kong}
      KONG_LICENSE_DATA: ${KONG_LICENSE_DATA}
      KONG_PG_SSL: "on"
      KONG_PG_SSL_VERIFY: "on"
      KONG_HEADERS: "off"
      KONG_ADMIN_GUI_FLAGS: '{"IMMUNITY_ENABLED":true}'
    links:
      - postgres:postgres
    networks:
      - kong-ee
    restart: on-failure
# Kong container
  kong-ee:
    image: kong-docker-kong-enterprise-edition-docker.bintray.io/kong-enterprise-edition:2.1.3.1-alpine
    user: "${KONG_USER:-root}"
    container_name: kong-ee
    networks:
      - kong-ee
    depends_on:
      - postgres
      - kong-migrations
    restart: on-failure
    ports:
      - "8000:8000/tcp"
      - "8001:8001/tcp"
      - "8002:8002/tcp"
      - "8003:8003/tcp"
      - "8004:8004/tcp"
      - "8443:8443/tcp"
      - "8444:8444/tcp"
      - "8445:8445/tcp"
      - "9444:9411/tcp"
    environment:
      KONG_ADMIN_LISTEN: 0.0.0.0:8001
      KONG_SMTP_MOCK: "off"
      KONG_CASSANDRA_CONTACT_POINTS: kong-ee-cassandra
      KONG_LICENSE_DATA: ${KONG_LICENSE_DATA}
      KONG_LOG_LEVEL: debug
      KONG_ADMIN_ACCESS_LOG: /dev/stdout
      KONG_ADMIN_ERROR_LOG: /dev/stderr
      KONG_ADMIN_GUI_URL: http://localhost:8002
      KONG_DATABASE: postgres
      KONG_PG_HOST: kong-ee-postgres
      KONG_PG_DATABASE: ${KONG_PG_DATABASE:-kong}
      KONG_PG_PASSWORD: ${KONG_PG_PASSWORD:-kong}
      KONG_PG_USER: ${KONG_PG_USER:-kong}
      KONG_PROXY_ACCESS_LOG: /dev/stdout
      KONG_PROXY_ERROR_LOG: /dev/stderr
      KONG_PLUGINS: bundled
      KONG_PASSWORD: kong
      KONG_ENFORCE_RBAC: "off"
      KONG_VITALS: "off"
# Redis container
  redis:
    image: redis:6.0.1-alpine
    container_name: redis-container
    networks:
      - kong-ee
    restart: on-failure
    ports:
        - "6379:6379"
    environment:
      REDIS_HOST: redis
networks:
  kong-ee:
