_format_version: "1.1"
_workspace: default
services:
- connect_timeout: 60000
  host: httpbin.org
  name: default
  path: /anything
  port: 443
  protocol: https
  read_timeout: 60000
  retries: 5
  write_timeout: 60000
  routes:
  - name: default
    paths:
    - /default
    path_handling: v0
    preserve_host: false
    protocols:
    - http
    regex_priority: 0
    strip_path: true
    https_redirect_status_code: 426
    request_buffering: true
    response_buffering: true
