version: "3"
services:

 kong1:
   image: ${KONG_IMAGE} #
   container_name: kong1
   networks:
    - kong
   restart: always
   command: "kong start"
   volumes:
    - ./default.yaml:/tmp/default.yaml
   ports:
    - 18000:8000
    - 18001:8001
    - 18002:8002
    - 18003:8003
    - 18004:8004
    - 18443:8443
    - 18444:8444
    - 18445:8445
    - 18446:8446
    - 18447:8447
   environment:
    - KONG_DATABASE=off
    - KONG_DECLARATIVE_CONFIG=/tmp/default.yaml
    - KONG_ANONYMOUS_REPORTS=off
#   - KONG_ENFORCE_RBAC=on
#   - KONG_ADMIN_GUI_AUTH=basic-auth
#   - KONG_ADMIN_GUI_SESSION_CONF={"secret":"secret","storage":"kong","cookie_secure":false}
    - KONG_AUDIT_LOG=on
    - KONG_LOG_LEVEL=debug 
    - KONG_PORTAL_GUI_PROTOCOL=http
    - KONG_PORTAL=on
    - KONG_PORTAL_AUTH=basic-auth
    - KONG_LICENSE_DATA=${KONG_LICENSE_DATA}
    - KONG_VITALS=on
    - KONG_PROXY_ACCESS_LOG=/dev/stdout
    - KONG_ADMIN_ACCESS_LOG=/dev/stdout
    - KONG_PROXY_ERROR_LOG=/dev/stderr
    - KONG_ADMIN_ERROR_LOG=/dev/stderr
    - KONG_ADMIN_API_URI=http://localhost:18001
    - KONG_PROXY_LISTEN=0.0.0.0:8000, 0.0.0.0:8443 ssl
    - KONG_STATUS_LISTEN=0.0.0.0:8100
    - KONG_ADMIN_LISTEN=0.0.0.0:8001, 0.0.0.0:8444 ssl
    - KONG_ADMIN_GUI_LISTEN=0.0.0.0:8002, 0.0.0.0:8445 ssl
    - KONG_PORTAL_GUI_LISTEN=0.0.0.0:8003, 0.0.0.0:8446 ssl
    - KONG_PORTAL_SESSION_CONF={"storage":"kong","cookie_name":"portal_session","secret":"super-secret","cookie_secure":false}
    - KONG_PORTAL_API_LISTEN=0.0.0.0:8004, 0.0.0.0:8447 ssl

 kong2:
   image: ${KONG_IMAGE} #
   container_name: kong2
   networks:
    - kong
   restart: always
   command: "kong start"
   volumes:
    - ./test.yaml:/tmp/test.yaml
   ports:
    - 28000:8000
    - 28001:8001
    - 28002:8002
    - 28003:8003
    - 28004:8004
    - 28443:8443
    - 28444:8444
    - 28445:8445
    - 28446:8446
    - 28447:8447
   environment:
    - KONG_DATABASE=off
    - KONG_DECLARATIVE_CONFIG=/tmp/test.yaml
    - KONG_ANONYMOUS_REPORTS=off
#   - KONG_ENFORCE_RBAC=on
#   - KONG_ADMIN_GUI_AUTH=basic-auth
#   - KONG_ADMIN_GUI_SESSION_CONF={"secret":"secret","storage":"kong","cookie_secure":false}
    - KONG_AUDIT_LOG=on
    - KONG_LOG_LEVEL=debug 
    - KONG_PORTAL_GUI_PROTOCOL=http
    - KONG_PORTAL=on
    - KONG_PORTAL_AUTH=basic-auth
    - KONG_LICENSE_DATA=${KONG_LICENSE_DATA}
    - KONG_VITALS=on
    - KONG_PROXY_ACCESS_LOG=/dev/stdout
    - KONG_ADMIN_ACCESS_LOG=/dev/stdout
    - KONG_PROXY_ERROR_LOG=/dev/stderr
    - KONG_ADMIN_ERROR_LOG=/dev/stderr
    - KONG_ADMIN_API_URI=http://localhost:28001
    - KONG_PROXY_LISTEN=0.0.0.0:8000, 0.0.0.0:8443 ssl
    - KONG_STATUS_LISTEN=0.0.0.0:8100
    - KONG_ADMIN_LISTEN=0.0.0.0:8001, 0.0.0.0:8444 ssl
    - KONG_ADMIN_GUI_LISTEN=0.0.0.0:8002, 0.0.0.0:8445 ssl
    - KONG_PORTAL_GUI_LISTEN=0.0.0.0:8003, 0.0.0.0:8446 ssl
    - KONG_PORTAL_SESSION_CONF={"storage":"kong","cookie_name":"portal_session","secret":"super-secret","cookie_secure":false}
    - KONG_PORTAL_API_LISTEN=0.0.0.0:8004, 0.0.0.0:8447 ssl

networks:
  kong:
    ipam:
      driver: default
      config: 
        - subnet: 10.0.0.0/24 